###get commisions
GET http://localhost:3001/api/commissions
Authorization: Bearer {{$dotenv TOKEN2}}
###get commisions
GET http://localhost:3001/api/referrals
Authorization: Bearer {{$dotenv TOKEN}}
###get commisions
GET http://localhost:3001/api/stats
Authorization: Bearer {{$dotenv TOKEN2}}
