####register
POST http://localhost:3001/api/register
Content-Type: application/json

{
    "name": "mimin",
    "email": "mamamn@gmail.com",
    "password": "santaikawan"
}
####login
POST http://localhost:3001/api/login
Content-Type: application/json

{
    "email": "mamamn@gmail.com",
    "password": "santaikawan"
}
####loginprodution
POST {{$dotenv PRODUCTION}}/api/login
Content-Type: application/json

{
    "email": "mamamn@gmail.com",
    "password": "santaikawan"
}
####rensed otp
POST http://localhost:3001/api/resend-otp
Content-Type: application/json
Authorization: Bearer {{$dotenv TOKEN}}

{
    "type": "email"
}
####verify otp
POST http://localhost:3001/api/verify-otp
Content-Type: application/json
Authorization: Bearer {{$dotenv TOKEN}}

{
    "code": "240987"
}
