###categories
POST http://localhost:3001/api/admin/categories
Content-Type: application/json
Authorization: Bearer {{$dotenv TOKEN}}

{
    "name": "minuman",
    "slug": "minuma",
    "description": "ini adalah makanan yang sanagt enak dan sanagt lejat"
}
###get
GET http://localhost:3001/api/categories
Authorization: Bearer {{$dotenv TOKEN}}
###get
DELETE http://localhost:3001/api/admin/categories/14
Authorization: Bearer {{$dotenv TOKEN}}
