###notification
POST http://localhost:3001/notifications
Content-Type: application/json
Authorization: Bearer {{$dotenv TOKEN}}

{
    "userId": 1,
    "title": "ini adalah notif",
    "message": "ini adalaha messgae",
    "type": "admin"
}

###get
GET http://localhost:3001/notifications
Content-Type: application/json
Authorization: Bearer {{$dotenv TOKEN}}
###delete
DELETE  http://localhost:3001/notifications/1
Content-Type: application/json
Authorization: Bearer {{$dotenv TOKEN}}
