###notification
POST http://localhost:3001/api/admin/notifications
Content-Type: application/json
Authorization: Bearer {{$dotenv TOKEN}}

{
    
    "title": "ini adalah notif",
    "message": "ini adalaha messgae",
    "type": "system"
}

###get
GET http://localhost:3001/api/admin/notifications
Content-Type: application/json
Authorization: Bearer {{$dotenv TOKEN}}
###readall
GET http://localhost:3001/api/notifications/read/all
Content-Type: application/json
Authorization: Bearer {{$dotenv TOKEN}}
###tandain yang sudah di baca
PATCH  http://localhost:3001/api/notifications/3/read
Content-Type: application/json
Authorization: Bearer {{$dotenv TOKEN}}
###delete
DELETE  http://localhost:3001/api/admin/notifications/18
Content-Type: application/json
Authorization: Bearer {{$dotenv TOKEN}}
