###get
GET http://localhost:3001/api/products
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwibmFtZSI6Im1pbWluIiwiZW1haWwiOiJtYW1hbW5AZ21haWwuY29tIiwic2Vzc2lvbktleSI6OCwiZXhwIjoxNzYxNTI4MTY0LCJpYXQiOjE3NjA5MjMzNjR9.vnFCpRKgR0DcrgIBC4eN5Jries87tCRozV0y4--XKJs
###post
POST  http://localhost:3001/api/admin/products
Authorization: Bearer {{$dotenv TOKEN}}
Content-Type: application/json

{
    "name": "minuman",
    "typeId": 1
    
}
###post
PUT  http://localhost:3001/api/admin/products/8
Authorization: Bearer {{$dotenv TOKEN}}
Content-Type: application/json

{
    "name": "makanan",
    "typeId": 1
    
}
###post
DELETE   http://localhost:3001/api/admin/products/8
Authorization: Bearer {{$dotenv TOKEN}}
Content-Type: application/json


###get production
GET {{$dotenv PRODUCTION}}/api/products
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwibmFtZSI6Im1pbWluIiwiZW1haWwiOiJtYW1hbW5AZ21haWwuY29tIiwic2Vzc2lvbktleSI6NCwiZXhwIjoxNzYxMjE3MTgyLCJpYXQiOjE3NjA2MTIzODJ9.GaREe329y7TWTT9VhJepyTJBnMJfZ6AcgyaTJh_yhec
