###get
GET http://localhost:3001/api/product-variants
Authorization: Bearer {{$dotenv TOKEN}}

###POST
POST http://localhost:3001/api/admin/product-variants
Authorization: Bearer {{$dotenv TOKEN}}
Content-Type: application/json

{
    "productId": 5,
    "name": "capcut 1 bulan",
    "duration": "1 bulan",
    "price": "80000",
    "originalPrice": "90000",
    "status":"READY"
}
###PUT
PUT http://localhost:3001/api/admin/product-variants/5
Content-Type: application/json
Authorization: Bearer {{$dotenv TOKEN}} 

{
    "productId": 5,
    "name": "capcut 3 bulan",
    "duration": "3 bulan",
    "price": "200000",
    "originalPrice": "250000",
    "status":"READY"
}

###delete
DELETE  http://localhost:3001/api/admin/product-variants/8
Authorization: Bearer {{$dotenv TOKEN}}
Content-Type: application/json
