###registe
POST http://localhost:3001/auth/register
Content-Type: application/json

{
    "name": "alwan ibrahim",
    "email": "alwanibrahim142@gmail.com",
    "password": "santaikawan"
}
###login
POST http://localhost:3001/auth/login
Content-Type: application/json

{
    "email": "alwanibrahim142@gmail.com",
    "password": "santaikawan"
}
###get
GET http://localhost:3001/auth/private/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6ImFsd2FuIGlicmFoaW0iLCJlbWFpbCI6ImFsd2FuaWJyYWhpbTE0MkBnbWFpbC5jb20iLCJzZXNzaW9uS2V5IjozLCJleHAiOjE3NjA3NjU2ODMsImlhdCI6MTc2MDE2MDg4M30.09thoWt4U7G7T0EMc2Se2F33-rN3qPucRSCWuvlFbDU
###get
POST  http://localhost:3001/test/ctx
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwibmFtZSI6ImFsd2FuIGlicmFoaW0iLCJlbWFpbCI6ImFsd2FuaWJyYWhpbTE0MkBnbWFpbC5jb20iLCJleHAiOjE3NjA2NjkyNjcsImlhdCI6MTc2MDA2NDQ2N30.-f2TIt5nmaNquO5WBxE_U9-WoEWcihi5dNARA4NMQoI

{
    "name": "alwanibrahim",
    "email": "alwanibrahim142@gmail.com",
    "password": "santaikawan"
}

###cookie
GET http://localhost:3001/test/cookie
Cookie: token=jdwehdil; theme=dark
###product
GET http://localhost:3001/products
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6ImFsd2FuIGlicmFoaW0iLCJlbWFpbCI6ImFsd2FuaWJyYWhpbTE0MkBnbWFpbC5jb20iLCJzZXNzaW9uS2V5Ijo4LCJleHAiOjE3NjA3NzUzNDEsImlhdCI6MTc2MDE3MDU0MX0.GctYILN_0caW5ixTrOre84tS1EMxe4HV_Wv2CmgOt78

###product
POST  http://localhost:3001/products
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6ImFsd2FuIGlicmFoaW0iLCJlbWFpbCI6ImFsd2FuaWJyYWhpbTE0MkBnbWFpbC5jb20iLCJzZXNzaW9uS2V5IjozLCJleHAiOjE3NjA3NjU2ODMsImlhdCI6MTc2MDE2MDg4M30.09thoWt4U7G7T0EMc2Se2F33-rN3qPucRSCWuvlFbDU
###get
Content-Type: application/json

{
    "name": "mimin",
    "type": "account",
    "price":"3000",
    "description": "barang nya sangat bagus",
    "originalPrice": 10000,
   "features": ["mantap","sangat tidak manuk akal", "ini yang saya suka"]


}
###product
DELETE   http://localhost:3001/products/6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6ImFsd2FuIGlicmFoaW0iLCJlbWFpbCI6ImFsd2FuaWJyYWhpbTE0MkBnbWFpbC5jb20iLCJzZXNzaW9uS2V5Ijo3LCJleHAiOjE3NjA3NzQ3MjEsImlhdCI6MTc2MDE2OTkyMX0.NjdJ2gcZtbchKP28Ci_CWPAmswyYasSIlZxW0luQgEE
###get
Content-Type: application/json


###categories
GET   http://localhost:3001/categories
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwibmFtZSI6ImFsd2FuIGlicmFoaW0iLCJlbWFpbCI6ImFsd2FuaWJyYWhpbTE0MkBnbWFpbC5jb20iLCJleHAiOjE3NjA3MDkzMTYsImlhdCI6MTc2MDEwNDUxNn0.Sc5IpMPScwDUxZYUv1iUpyZJ60khNEGQ6qzKxfVMim4
Content-Type: application/json

###deposite
GET   http://localhost:3001/deposites
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwibmFtZSI6ImFsd2FuIGlicmFoaW0iLCJlbWFpbCI6ImFsd2FuaWJyYWhpbTE0MkBnbWFpbC5jb20iLCJleHAiOjE3NjA3MDkzMTYsImlhdCI6MTc2MDEwNDUxNn0.Sc5IpMPScwDUxZYUv1iUpyZJ60khNEGQ6qzKxfVMim4
Content-Type: application/json


###commisison
GET   http://localhost:3001/commisions
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwibmFtZSI6ImFsd2FuIGlicmFoaW0iLCJlbWFpbCI6ImFsd2FuaWJyYWhpbTE0MkBnbWFpbC5jb20iLCJleHAiOjE3NjA3MDkzMTYsImlhdCI6MTc2MDEwNDUxNn0.Sc5IpMPScwDUxZYUv1iUpyZJ60khNEGQ6qzKxfVMim4
Content-Type: application/json

###notif
GET   http://localhost:3001/notifications
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwibmFtZSI6ImFsd2FuIGlicmFoaW0iLCJlbWFpbCI6ImFsd2FuaWJyYWhpbTE0MkBnbWFpbC5jb20iLCJleHAiOjE3NjA3MDkzMTYsImlhdCI6MTc2MDEwNDUxNn0.Sc5IpMPScwDUxZYUv1iUpyZJ60khNEGQ6qzKxfVMim4
Content-Type: application/json


